<a href="https://colab.research.google.com/github/nurfnick/Mathematical_Musings/blob/main/Generating_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Generating Functions

I've been working through the Applied Discrete Structures book for my class.  I was curious about the following question and could not do it by hand.

>Suppose that you roll a die ten times in a row and record the square of each number that you roll. How many ways could the sum of the
squares of your rolls equal 40? What is the most common outcome?

In [1]:
from sympy import *

x= Symbol('x')

f = (x+x**4+x**9+x**16+x**25+x**36)**10

In [2]:
f.expand()

x**360 + 10*x**349 + 10*x**340 + 45*x**338 + 10*x**333 + 90*x**329 + 10*x**328 + 120*x**327 + 10*x**325 + 90*x**322 + 45*x**320 + 360*x**318 + 90*x**317 + 210*x**316 + 90*x**314 + 90*x**313 + 360*x**311 + 360*x**309 + 90*x**308 + 840*x**307 + 405*x**306 + 342*x**305 + 360*x**303 + 720*x**302 + 90*x**301 + 960*x**300 + 1350*x**298 + 720*x**297 + 1305*x**296 + 1200*x**295 + 930*x**294 + 450*x**293 + 840*x**292 + 2520*x**291 + 765*x**290 + 2100*x**289 + 360*x**288 + 3240*x**287 + 2880*x**286 + 1980*x**285 + 2520*x**284 + 2640*x**283 + 3240*x**282 + 1980*x**281 + 5250*x**280 + 3000*x**279 + 4500*x**278 + 2520*x**277 + 6030*x**276 + 7560*x**275 + 4980*x**274 + 5340*x**273 + 5085*x**272 + 10440*x**271 + 6660*x**270 + 7920*x**269 + 7980*x**268 + 10080*x**267 + 9540*x**266 + 10920*x**265 + 13980*x**264 + 13320*x**263 + 14070*x**262 + 9190*x**261 + 20412*x**260 + 19320*x**259 + 13590*x**258 + 16380*x**257 + 20940*x**256 + 25320*x**255 + 22680*x**254 + 22260*x**253 + 26130*x**252 + 33120*x**251 

The number of times 40 will appear is the coefficient of $x^{40}$ or 4186.  As for the most frequent, I think it is 145 at a whopping 666 742 times.  Let's algorithmically check this

In [12]:
newf = f
m = 0
for i in range(360):
  newf = diff(newf,x)
  m = max(m,newf.subs(x,0)/factorial(i+1))

KeyboardInterrupt: ignored

In [13]:
m

130

This runs incredibly slow.  360 derivatives is asking for a lot...  `sympy` should have a built-in...

In [16]:
coeff = Poly(f).all_coeffs()

max(coeff)

675720

Looks like I didn't find the max!  What position is it in?

In [17]:
coeff.index(max(coeff))

211

211 is not the power though, just the position in the list.  The list has been reversed.

In [19]:
360-211

149

I wonder if I can gain insight as to why this is the most common number to appear in the list

In [20]:
sum = 0
for i in range(1,7):
  sum += i**2

In [24]:
sum/6*10

151.66666666666666

I'd actually expect the mean to have the highest concentration of options but I should keep in mind that this is not normally distributed...